"""Serve the Astrion remote's layout: YAML in, JSON out.

The custom Astrion app (com.custom.astrion) pulls its layout over HTTP. Authoring
that layout in JSON was awkward — it lives in this config repo alongside
configuration.yaml / automations.yaml / dashboards/*.yaml, it is hand-edited, and
JSON has no comments, while the file encodes plenty of non-obvious behaviour
(`open_on`, `scroll_to` anchors, `active_value` strings that must match HA state
exactly).

Rather than add a YAML parser to the app — Android has none built in, so it would
mean a ~300 KB-1 MB reflective dependency on a 1.3 MB APK running on a 1 GB
MT6580 — this component keeps the source of truth in YAML and serves it as JSON:

    astrion/dashboard.yaml  ->  GET /api/astrion_dashboard

No generated file to fall out of sync (the old www/astrion/dashboard.json had to
be regenerated by hand), and unlike /local/ this endpoint requires auth — the app
already sends its bearer token.

Because it uses HA's own YAML loader, `!include` works, so the layout can be
split into per-page files later if it grows.

Config (configuration.yaml):

    astrion_dashboard:
      path: astrion/dashboard.yaml   # optional, this is the default
"""
from __future__ import annotations

import logging
import os

import voluptuous as vol
from aiohttp import web

from homeassistant.components.http import HomeAssistantView
from homeassistant.core import HomeAssistant
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers.typing import ConfigType
from homeassistant.util.yaml import load_yaml

_LOGGER = logging.getLogger(__name__)

DOMAIN = "astrion_dashboard"
DEFAULT_PATH = "astrion/dashboard.yaml"

CONFIG_SCHEMA = vol.Schema(
    {DOMAIN: vol.Schema({vol.Optional("path", default=DEFAULT_PATH): cv.string})},
    extra=vol.ALLOW_EXTRA,
)


async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    """Register the layout endpoint."""
    conf = config.get(DOMAIN) or {}
    rel_path = conf.get("path", DEFAULT_PATH)
    path = hass.config.path(rel_path)
    hass.http.register_view(AstrionDashboardView(path))
    _LOGGER.info("astrion_dashboard: serving %s at /api/%s", path, DOMAIN)
    return True


class AstrionDashboardView(HomeAssistantView):
    """Return the YAML layout as JSON for the Astrion app."""

    url = f"/api/{DOMAIN}"
    name = f"api:{DOMAIN}"
    # The app authenticates with the same long-lived token it uses for the
    # websocket, so the layout isn't world-readable the way /local/ is.
    requires_auth = True

    def __init__(self, path: str) -> None:
        self._path = path

    async def get(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        try:
            data = await hass.async_add_executor_job(self._load)
        except FileNotFoundError:
            return self.json_message(
                f"{os.path.basename(self._path)} not found", status_code=404
            )
        except Exception as err:  # noqa: BLE001 - surface parse errors to the client
            _LOGGER.error("astrion_dashboard: failed to load %s: %s", self._path, err)
            return self.json_message(f"invalid YAML: {err}", status_code=500)
        return self.json(data)

    def _load(self):
        """Read + parse the YAML (blocking; runs in the executor)."""
        return load_yaml(self._path)
